"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (autogenerate emits this for JSONB variants)
from sqlalchemy.dialects import postgresql  # noqa: F401

# Every table in this schema uses the custom type decorators, and autogenerate
# emits fully-qualified references to them without adding the import. Four
# consecutive migrations shipped with a NameError because of it, so the import
# is unconditional here rather than left to the autogenerated import block
# below.
import mybot_schemas.db.types  # noqa: F401
${imports if imports else ""}

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
