"""egress ledger

Records, per model call, whether it left the machine and where it went.

Both columns are nullable on purpose. Rows written before this migration have
no answer, and backfilling them with ``False`` would make the ledger assert
that nothing left during a period it has no record of. NULL means unknown, and
the ledger reports unknowns as unknowns.

Revision ID: d820e462a04e
Revises: c080dba6424e
Create Date: 2026-08-12 16:12:31.590302
"""
from alembic import op
import sqlalchemy as sa


revision = 'd820e462a04e'
down_revision = 'c080dba6424e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_machine', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=255), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_column('destination')
        batch_op.drop_column('left_machine')

    # ### end Alembic commands ###
