"""learned preferences

The table that makes one MyBot different from every other one.

Revision ID: c080dba6424e
Revises: 13ba27dc4e67
Create Date: 2026-08-12 15:25:43.510372
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import mybot_schemas.db.types

revision = 'c080dba6424e'
down_revision = '13ba27dc4e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_preferences',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_observed_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('last_observed_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_owner', sa.Boolean(), nullable=False),
    sa.Column('derived_from_untrusted', sa.Boolean(), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'kind', 'subject', name='uq_learned_subject')
    )
    with op.batch_alter_table('learned_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_learned_owner_kind', ['owner_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_learned_preferences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learned_preferences_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learned_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learned_preferences_owner_id'))
        batch_op.drop_index(batch_op.f('ix_learned_preferences_created_at'))
        batch_op.drop_index('ix_learned_owner_kind')

    op.drop_table('learned_preferences')
    # ### end Alembic commands ###
