"""notification dedupe key

Revision ID: 13ba27dc4e67
Revises: 878b28722c1c
Create Date: 2026-08-12 14:55:37.703531
"""
import sqlalchemy as sa
from alembic import op

revision = '13ba27dc4e67'
down_revision = '878b28722c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dedupe_key', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint('uq_notification_dedupe', ['owner_id', 'dedupe_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notification_dedupe', type_='unique')
        batch_op.drop_column('dedupe_key')

    # ### end Alembic commands ###
