"""connector egress events

Revision ID: 9b576a0dab4d
Revises: d820e462a04e
Create Date: 2026-08-12 16:43:04.232423
"""
from alembic import op
import sqlalchemy as sa

import mybot_schemas.db.types


revision = '9b576a0dab4d'
down_revision = 'd820e462a04e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egress_events',
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('left_machine', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('egress_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_egress_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_egress_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_egress_owner_at', ['owner_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egress_events', schema=None) as batch_op:
        batch_op.drop_index('ix_egress_owner_at')
        batch_op.drop_index(batch_op.f('ix_egress_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_egress_events_created_at'))

    op.drop_table('egress_events')
    # ### end Alembic commands ###
