"""Initial MyBot schema

Revision ID: 878b28722c1c
Revises: 
Create Date: 2026-08-12 14:14:48.087399
"""
import mybot_schemas.db.types
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '878b28722c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('strong_auth_ref', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('action_proposals',
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('base_risk', sa.String(length=16), nullable=False),
    sa.Column('requested_by_type', sa.String(length=16), nullable=False),
    sa.Column('requested_by_id', sa.String(length=200), nullable=True),
    sa.Column('requested_by_label', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('derived_from_untrusted', sa.Boolean(), nullable=False),
    sa.Column('untrusted_source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('required_auth_level', sa.String(length=16), nullable=False),
    sa.Column('policy_outcome', sa.String(length=32), nullable=True),
    sa.Column('policy_rule_id', sa.String(length=64), nullable=True),
    sa.Column('policy_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('expires_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('execution_outcome', sa.String(length=32), nullable=True),
    sa.Column('execution_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('executed_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('llm_run_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_action_idempotency')
    )
    with op.batch_alter_table('action_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_proposals_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_proposals_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_actions_owner_status', ['owner_id', 'status'], unique=False)

    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('policy_rule', sa.String(length=64), nullable=True),
    sa.Column('approval_method', sa.String(length=32), nullable=True),
    sa.Column('approval_auth_level', sa.String(length=16), nullable=True),
    sa.Column('integration', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'sequence', name='uq_audit_owner_sequence')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_hash'), ['event_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_owner_seq', ['owner_id', 'sequence'], unique=False)

    op.create_table('automation_rules',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('action_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_owner_id'), ['owner_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('calendar_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('start_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('end_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('attendees', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('organizer', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider', 'external_id', name='uq_calevent_external')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_calevent_owner_start', ['owner_id', 'start_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('conversation_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('llm_run_id', sa.String(length=36), nullable=True),
    sa.Column('action_proposal_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_chat_owner_conv', ['owner_id', 'conversation_id'], unique=False)

    op.create_table('credential_references',
    sa.Column('ref', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_used_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'ref', name='uq_credref_ref')
    )
    with op.batch_alter_table('credential_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_references_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_references_owner_id'), ['owner_id'], unique=False)

    op.create_table('daily_briefs',
    sa.Column('brief_date', sa.String(length=10), nullable=False),
    sa.Column('greeting', sa.String(length=200), nullable=False),
    sa.Column('needs_you', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('handled', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'brief_date', name='uq_brief_day')
    )
    with op.batch_alter_table('daily_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_briefs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_briefs_owner_id'), ['owner_id'], unique=False)

    op.create_table('devices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('attestation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('can_provide_physical_presence', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_owner_id'), ['owner_id'], unique=False)

    op.create_table('email_messages',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('to_addresses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('received_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('classification_label', sa.String(length=32), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('requires_reply', sa.Boolean(), nullable=False),
    sa.Column('replied_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('injection_suspected', sa.Boolean(), nullable=False),
    sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider', 'external_id', name='uq_email_external')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_email_owner_received', ['owner_id', 'received_at'], unique=False)

    op.create_table('entities',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('merged_into_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inferred', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('deleted_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_entities_owner_name', ['owner_id', 'name'], unique=False)
        batch_op.create_index('ix_entities_owner_type', ['owner_id', 'entity_type'], unique=False)

    op.create_table('integrations',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('credential_ref', sa.String(length=200), nullable=True),
    sa.Column('account_label', sa.String(length=200), nullable=True),
    sa.Column('last_sync_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('write_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider', name='uq_integration_provider')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_owner_id'), ['owner_id'], unique=False)

    op.create_table('llm_runs',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('max_classification_sent', sa.String(length=20), nullable=False),
    sa.Column('pii_tokenized', sa.Boolean(), nullable=False),
    sa.Column('contained_untrusted', sa.Boolean(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_request_id'), ['request_id'], unique=False)

    op.create_table('notifications',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('inbox_item_id', sa.String(length=36), nullable=True),
    sa.Column('action_proposal_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('delivered_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_owner_id'), ['owner_id'], unique=False)

    op.create_table('permission_rules',
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('allowed_recipients', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('allowed_time_window', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('requires_strong_auth', sa.Boolean(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('allow_automatic', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_auth_level', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission_rules', schema=None) as batch_op:
        batch_op.create_index('ix_perm_owner_action', ['owner_id', 'action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_rules_owner_id'), ['owner_id'], unique=False)

    op.create_table('pii_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('value_ref', sa.String(length=200), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'token', name='uq_pii_token'),
    sa.UniqueConstraint('owner_id', 'value_hash', name='uq_pii_value')
    )
    with op.batch_alter_table('pii_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pii_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pii_tokens_owner_id'), ['owner_id'], unique=False)

    op.create_table('security_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_owner_id'), ['owner_id'], unique=False)

    op.create_table('security_states',
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('locked_reason', sa.String(length=300), nullable=True),
    sa.Column('locked_by', sa.String(length=200), nullable=True),
    sa.Column('automations_enabled', sa.Boolean(), nullable=False),
    sa.Column('approval_epoch', sa.Integer(), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_security_state_owner')
    )
    with op.batch_alter_table('security_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_states_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_states_owner_id'), ['owner_id'], unique=False)

    op.create_table('sources',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('external_ref', sa.String(length=300), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('trust', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_owner_id'), ['owner_id'], unique=False)

    op.create_table('vault_secrets',
    sa.Column('ref', sa.String(length=200), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('aad', sa.String(length=300), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('rotated_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'ref', name='uq_vault_ref')
    )
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_secrets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vault_secrets_owner_id'), ['owner_id'], unique=False)

    op.create_table('action_approvals',
    sa.Column('proposal_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('auth_level', sa.String(length=16), nullable=False),
    sa.Column('approver_user_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('consumed_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('invalidated_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('invalidated_reason', sa.String(length=200), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['action_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_approvals_owner_id'), ['owner_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('device_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('auth_level', sa.String(length=16), nullable=False),
    sa.Column('elevated_until', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('expires_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('documents',
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('folder', sa.String(length=200), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=32), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('entity_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('deleted_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('facts',
    sa.Column('entity_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('observed_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('superseded_by_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('superseded_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inferred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_facts_owner_entity_key', ['owner_id', 'entity_id', 'key'], unique=False)
        batch_op.create_index(batch_op.f('ix_facts_owner_id'), ['owner_id'], unique=False)

    op.create_table('memories',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('entity_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('structured', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('superseded_by_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('last_used_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inferred', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('deleted_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['memories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_memories_owner_kind', ['owner_id', 'kind'], unique=False)

    op.create_table('obligations',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('recurrence', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('entity_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('recommended_action_type', sa.String(length=64), nullable=True),
    sa.Column('depends_on_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('remind_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inferred', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('deleted_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligations_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_obligations_owner_due', ['owner_id', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_obligations_owner_status', ['owner_id', 'status'], unique=False)

    op.create_table('relationships',
    sa.Column('from_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('to_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('valid_from', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('valid_to', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('inferred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'from_id', 'to_id', 'relation_type', name='uq_relationship_triple')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index('ix_rel_owner_from', ['owner_id', 'from_id'], unique=False)
        batch_op.create_index('ix_rel_owner_to', ['owner_id', 'to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_owner_id'), ['owner_id'], unique=False)

    op.create_table('inbox_items',
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('obligation_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('entity_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('action_proposal_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=True),
    sa.Column('possible_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('recommended_action', sa.String(length=300), nullable=True),
    sa.Column('due_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('snoozed_until', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('resolved_at', mybot_schemas.db.types.UTCDateTime(), nullable=True),
    sa.Column('id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('owner_id', mybot_schemas.db.types.UUIDStr(length=36), nullable=False),
    sa.Column('created_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', mybot_schemas.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'dedupe_key', name='uq_inbox_dedupe')
    )
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_items_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_inbox_owner_state', ['owner_id', 'state'], unique=False)

    # ### end Alembic commands ###


    # ------------------------------------------------------------------
    # Audit immutability, at the storage layer.
    #
    # The ORM already refuses to modify or delete an audit row, but that guard
    # lives in the application process -- which the threat model assumes will
    # eventually be compromised. These triggers survive that: even a caller
    # holding a raw connection cannot rewrite history.
    # ------------------------------------------------------------------
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute(
            """
            CREATE TRIGGER IF NOT EXISTS audit_events_no_update
            BEFORE UPDATE ON audit_events
            BEGIN
                SELECT RAISE(ABORT, 'audit_events is append-only');
            END;
            """
        )
        op.execute(
            """
            CREATE TRIGGER IF NOT EXISTS audit_events_no_delete
            BEFORE DELETE ON audit_events
            BEGIN
                SELECT RAISE(ABORT, 'audit_events is append-only');
            END;
            """
        )
    elif bind.dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION mybot_audit_append_only()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_events is append-only';
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_no_update
            BEFORE UPDATE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION mybot_audit_append_only();
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_no_delete
            BEFORE DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION mybot_audit_append_only();
            """
        )


def downgrade() -> None:
    bind = op.get_bind()
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_update ON audit_events"
               if bind.dialect.name == "postgresql"
               else "DROP TRIGGER IF EXISTS audit_events_no_update")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_delete ON audit_events"
               if bind.dialect.name == "postgresql"
               else "DROP TRIGGER IF EXISTS audit_events_no_delete")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_index('ix_inbox_owner_state')
        batch_op.drop_index(batch_op.f('ix_inbox_items_owner_id'))
        batch_op.drop_index(batch_op.f('ix_inbox_items_created_at'))

    op.drop_table('inbox_items')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_owner_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_created_at'))
        batch_op.drop_index('ix_rel_owner_to')
        batch_op.drop_index('ix_rel_owner_from')

    op.drop_table('relationships')
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.drop_index('ix_obligations_owner_status')
        batch_op.drop_index(batch_op.f('ix_obligations_owner_id'))
        batch_op.drop_index('ix_obligations_owner_due')
        batch_op.drop_index(batch_op.f('ix_obligations_created_at'))
        batch_op.drop_index(batch_op.f('ix_obligations_archived'))

    op.drop_table('obligations')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memories_owner_kind')
        batch_op.drop_index(batch_op.f('ix_memories_owner_id'))
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))
        batch_op.drop_index(batch_op.f('ix_memories_archived'))

    op.drop_table('memories')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_owner_id'))
        batch_op.drop_index('ix_facts_owner_entity_key')
        batch_op.drop_index(batch_op.f('ix_facts_created_at'))

    op.drop_table('facts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_archived'))

    op.drop_table('documents')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_created_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('action_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_approvals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_action_approvals_created_at'))

    op.drop_table('action_approvals')
    with op.batch_alter_table('vault_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_secrets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_vault_secrets_created_at'))

    op.drop_table('vault_secrets')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_owner_id'))
        batch_op.drop_index(batch_op.f('ix_sources_external_ref'))
        batch_op.drop_index(batch_op.f('ix_sources_created_at'))

    op.drop_table('sources')
    with op.batch_alter_table('security_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_states_owner_id'))
        batch_op.drop_index(batch_op.f('ix_security_states_created_at'))

    op.drop_table('security_states')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_created_at'))

    op.drop_table('security_events')
    with op.batch_alter_table('pii_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pii_tokens_owner_id'))
        batch_op.drop_index(batch_op.f('ix_pii_tokens_created_at'))

    op.drop_table('pii_tokens')
    with op.batch_alter_table('permission_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_rules_owner_id'))
        batch_op.drop_index(batch_op.f('ix_permission_rules_created_at'))
        batch_op.drop_index('ix_perm_owner_action')

    op.drop_table('permission_rules')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_owner_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_runs_request_id'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_llm_runs_created_at'))

    op.drop_table('llm_runs')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_created_at'))

    op.drop_table('integrations')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_owner_type')
        batch_op.drop_index('ix_entities_owner_name')
        batch_op.drop_index(batch_op.f('ix_entities_owner_id'))
        batch_op.drop_index(batch_op.f('ix_entities_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_entities_created_at'))
        batch_op.drop_index(batch_op.f('ix_entities_archived'))

    op.drop_table('entities')
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_email_owner_received')
        batch_op.drop_index(batch_op.f('ix_email_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_owner_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_created_at'))

    op.drop_table('email_messages')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_owner_id'))
        batch_op.drop_index(batch_op.f('ix_devices_created_at'))

    op.drop_table('devices')
    with op.batch_alter_table('daily_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_briefs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_daily_briefs_created_at'))

    op.drop_table('daily_briefs')
    with op.batch_alter_table('credential_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_references_owner_id'))
        batch_op.drop_index(batch_op.f('ix_credential_references_created_at'))

    op.drop_table('credential_references')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_owner_conv')
        batch_op.drop_index(batch_op.f('ix_chat_messages_owner_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_calevent_owner_start')
        batch_op.drop_index(batch_op.f('ix_calendar_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_created_at'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rules_owner_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_created_at'))

    op.drop_table('automation_rules')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_owner_seq')
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_hash'))

    op.drop_table('audit_events')
    with op.batch_alter_table('action_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_owner_status')
        batch_op.drop_index(batch_op.f('ix_action_proposals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_action_proposals_created_at'))
        batch_op.drop_index(batch_op.f('ix_action_proposals_action_type'))

    op.drop_table('action_proposals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
